project_id = "qiqxdivyyjcbegdlptuq"

[functions.send-auth-email]
verify_jwt = false

[functions.send-application-status]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true

[functions.company-lookup]
verify_jwt = false

[functions.account-lookup]
verify_jwt = false

[functions.add-company-member]
verify_jwt = false